### ISSUE TITLE
Not work in mobile

### ISSUE THREAD

**Issue by jacsamg** [lf2com/knob.js#12]
Thank you for this amazing library. I have used it in a project. It works perfectly with the mouse. However, for some reason, it doesn't work on a cell phone's touch screen.

**Comment by lf2com** [comment]
Hi @tojacob,
I found that issue was supposed to be related to `PointerEvent` I used. I change it to `MouseEvent` and 'TouchEvent` then the issue seems to be fixed. A new version with this change is available: [v2.0.2](https://github.com/lf2com/knob.js/releases/tag/v2.0.2).

**Comment by jacsamg** [comment]
The problem is solved. Thank you!
